### ISSUE TITLE
Typechecking failed after update from 0.2.2 to 0.2.3

### ISSUE THREAD

**Issue by cawa-93** [johnsoncodehk/vue-tsc#61]
See [this](https://github.com/cawa-93/anime-library/pull/152/checks?check_run_id=3333393048) workflow run.
After update to 0.2.3 I got many errors like this:
```node

Error: packages/renderer/src/components/Options/ColorScheme.vue(5,7): error TS2322: Type '"system" | "light" | "dark"' is not assignable to type 'Booleanish | undefined'.
  Type '"system"' is not assignable to type 'Booleanish | undefined'.
```

Example of affected component:
https://github.com/cawa-93/anime-library/blob/7173ca67072c7025ab354f9b08003e549fdea03b/packages/renderer/src/components/Options/ColorScheme.vue

**Comment by johnsoncodehk** [comment]
This is upstream problem. See #57, #58, https://github.com/vuejs/vue-next/issues/4321, https://github.com/vuejs/vue-next/issues/4322.

You can lock vue-tsc to 0.2.2 and lock vscode-vue-languageservice to 0.26.14 for now.

**Comment by zigomir** [comment]
Is there a way to ignore this error for now? I couldn't find a way to put `@ts-ignore` inside `v-model`…

**Comment by johnsoncodehk** [comment]
@zigomir vue already resolved it in 3.2.3! But [Evan point out radio v-model prop incorrect in volar](https://github.com/vuejs/vue-next/issues/4321#issuecomment-899824298), I will fix it soon.

**Comment by johnsoncodehk** [comment]
> @zigomir vue already resolved it in 3.2.3! But [Evan point out radio v-model prop incorrect in volar](https://github.com/vuejs/vue-next/issues/4321#issuecomment-899824298), I will fix it soon.

Fix in vscode-vue-languageservice 0.27.2.

**Comment by cawa-93** [comment]
@johnsoncodehk Could you, please, release new vue-tsc with that fix?

**Comment by johnsoncodehk** [comment]
@cawa-93 you can delete yarn.lock / package-lock.json and reinstall to update vscode-vue-languageservice.
